In [1]:
import numpy as np

In [2]:
# Reshaping in Arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [4]:
flattened = arr.flatten() #2D -> 1D
print(flattened, flattened.shape)

[1 2 3 4 5 6] (6,)
