In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Properties
print(arr.shape) #dimensions = m x n
print(arr.size)  #total elements
print(arr.dtype) 
print(arr.ndim)

(3, 3)
9
int64
2


In [3]:
#type casting
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
