In [5]:
import numpy as np

In [6]:
#Slicing in Array
arr = np.array([1, 2, 3, 4, 5])

#[start, end, step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [7]:
#copy vs view

#copy (python lists)
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)

sub_list[0] = 200

print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [8]:
#view (numpy arrays)
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]
