In [2]:
import numpy as np

In [3]:
#Indexing on 1-D array
arr = np.array([1, 2, 3, 4, 5])

print(arr[0]) 
print(arr[3])

1
4


In [4]:
#Indexing on 2-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2[1][1])
print(arr2[0][2])

5
3


In [6]:
#Fancy Indexing
arr3 = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr3[idx])

[1 2 4]


In [9]:
#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]
